### ISSUE TITLE
G6官网的例子无法查看源码了

### ISSUE THREAD

**Issue by jtyjty99999** [antvis/antvis.github.io#145]
https://antv-g6.gitee.io/zh/examples/case/largeGraph#index

![image](https://github.com/antvis/antvis.github.io/assets/893152/1f85e0fe-2b06-462a-b021-9db718e58498)

点击查看源码，访问下面的链接：

https://github.com/antvis/G6/blob/master/site/pages/largegraph.zh.tsx

已经404了

**Comment by hustcc** [comment]
请访问地址 g6.antv.antgroup.com
