### ISSUE TITLE
蚂蚁金服发布专业可视化规范 AntV

### ISSUE THREAD

**Issue by hi-caicai** [antvis/antvis.github.io#2]
注: 用pc浏览器打开，效果更好（微信中打开会被屏蔽，建议用pc浏览器打开）

今天蚂蚁金服发布了一套数据可视化规范AntV。

AntV 是一套专业的数据可视化规范，这套规范的目的是为了让可视化的使用者更懂数据可视化。这套规范是蚂蚁金服在可视化建设过程中的理论沉淀，它可以很好得指引`产品经理`，`设计师`和`工程师`怎样正确得使用可视化及可视化技术，规避常见的错误，可以当学习材料，也可以作为手册使用。

![image](https://os.alipayobjects.com/rmsportal/PFajrSPDWpaKjIS.png)

官方地址：[https://antv.alipay.com/](https://antv.alipay.com/)
## 30 多种可视化图表的详细介绍

规范中总结了常用的 30 多种图表的特性（不断增加）。每篇图表介绍中包括：`基本介绍`，`图表起源`，`图表的构成`，`图表的应用场景`，`错误的使用场景`，`该图表的扩展及该图表`[G2](https://g2.alipay.com/)`引擎上的实现`。

![image](https://os.alipayobjects.com/rmsportal/WPbISTnQHeOyVkc.png)

![image](https://os.alipayobjects.com/rmsportal/ZijkAGQJiolSYwP.png)

![image](https://os.alipayobjects.com/rmsportal/FruUJZaklgeeGIH.png)

它是图表的`一站式`站点
## 图表分类

AntV为这些图表做了一系列的分类，更好的组织这些图表，使用者进来后可以根据自己的目的很容易找到对应的图表。

![image](https://os.alipayobjects.com/rmsportal/ZynpBrODzBSJMZH.png)
## 设计规范

AntV内置了一套设计规范，这个[设计规范](https://antv.alipay.com/design/index.html)可以很好的指导设计师为图表选择合适的设计元素。

![image](https://os.alipayobjects.com/rmsportal/msNRxzdcstqaGtn.png)
# 欢迎使用及反馈

欢迎使用 [https://antv.alipay.com/](https://antv.alipay.com/)

您使用这套规范中，如果您发现哪里写的不准确或者有更好的建议，请在这个页面给我们反馈。[https://github.com/antvis/feedback/issues/new](https://github.com/antvis/feedback/issues/new)

该规范中的所有图表均有G2可视化引擎实现，欢迎查看[http://g2.alipay.com/](http://g2.alipay.com/)。

**Comment by airyland** [comment]
Cool
