### ISSUE TITLE
各子产品首页的“图表示例”链接路径有问题

### ISSUE THREAD

**Issue by paleface001** [antvis/antvis.github.io#29]
![image](https://user-images.githubusercontent.com/5888974/69007892-e0c8b280-097e-11ea-9073-a63c22f042be.png)

刚试了下g2 g6 l7 g2plot的都不行

**Comment by afc163** [comment]
https://github.com/antvis/gatsby-theme-antv/blob/c888dca406850c89253cb6aa1bca4fb0927fe690/%40antv/gatsby-theme-antv/site/components/Banner.tsx#L139

这里要用 Link，Link 会自动带上 pathPrefix。

@Yanyan-Wang

**Comment by afc163** [comment]
@Yanyan-Wang 修复了 commit 关联上 issue。

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang 修复了 commit 关联上 issue。
> 
> 看下 https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

好的

**Comment by Yanyan-Wang** [comment]
已解决
