### ISSUE TITLE
Unexpected Redirection!

### ISSUE THREAD

**Issue by Cecil0o0** [antvis/antvis.github.io#46]
When I visit the url "https://antv.alipay.com/zh-cn/vis/chart/venn.html#_%E9%9F%A6%E6%81%A9%E5%9B%BE", it always redirect to "https://antv.vision" which is annoying.

Please spend some time to figure it out for user's experience~

Thx!

**Comment by afc163** [comment]
If you are try visit our old site, please try https://antv-2018.alipay.com/zh-cn/vis/chart/venn.html#_%E9%9F%A6%E6%81%A9%E5%9B%BE

**Comment by Cecil0o0** [comment]
Unfortunately, I confirmed that I was trying to search on the website "
https://antv.vision/".

I texted "venn" in Input Control on the top of page, and the dropdown
showed, then it was redirected to "https://ant.vision" again after I
clicked the first item.


Maybe a screen capture talks more than words.
[image: image.png]


And I'm sorry for that I didn't express clearly. -_-!
