### ISSUE TITLE
首页的图表分类效果优化

### ISSUE THREAD

**Issue by raisezhang** [antvis/antvis.github.io#54]
之前有过类似图谱的需求

在展开下一级的情况下，如果上一级还展示，数据会比较乱，上级展示也没有多大意义（也许有一点是用户不知道再次点击回到上级）。

所以想的是把父类的关闭，这样数据展示会比较直观。

之前写过的例子 ： [Example](http://m.fengniaocaijing.com/activity/blockchain-ecosystem)

**Comment by afc163** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/507615/73806158-ac3cf800-4803-11ea-963c-8284767b0c04.png">

**Comment by afc163** [comment]
已经完成改版，具体效果见：https://antv.vision/zh
