### ISSUE TITLE
能否关闭文档页面的平滑滚动

### ISSUE THREAD

**Issue by shinima** [antvis/antvis.github.io#62]
现在新版的文档网站全部开启了平滑滚动，这个特性导致了页面使用效率不高。尤其是在内容比较多的页面中进行搜索时（例如 https://g2.antv.vision/zh/docs/api/g2 ），页面滚动占用了过多时间，能否关闭平滑滚动特性，或是加快一下页面的滚动速度？

**Comment by afc163** [comment]
https://github.com/antvis/gatsby-theme-antv/issues/93

@simaQ
